---
title: "cardiovascular disease in a metabolic framework"
---

Cardiovascular mortality has been declining since the 1970s in nearly all regions of the world, especially in high-income countries such as North America, Western Europe, Japan, Australia, New Zealand and Denmark[@gbd2013mortalityandcausesofdeathcollaborators2015; @moran2014; @roth2015; @dramatis], and this can be explained by numerous different trends. In the first half of the 20th century, life expectancy dramatically increased as a result of improved sanitation, vaccines, and antibiotics, and suddenly people lived long enough to experience atherosclerosis, heart disease, and cancer, that together replaced infectious diseases as leading causes of death[@mensah2017]. However, in the 1970's, epidemiologists from the United States and Australia published studies showing that coronary heart disease mortality surprisingly had begun to decline after peaking in the late 1960's[@rogers1977; @reader1972], and they were later accompanied by epidemiologists showing similar declines in other regions (DK, Norge?). The declining trend in cardiovascular mortality has continued since and has been explained partly by progress in evidence-based medicine and surgical practices and continuously improved secondary prevention after a cardiovascular event, and partly by changes in risk factors including reductions in low-density lipoprotein cholesterol, systolic blood pressure, and smoking. There is however a problem that is likely to manifest itself in the cardiovascular disease mortality trends in the next few decades and not only be limited to some population groups. Because, while overall cardiovascular mortality is declining,

Additionally, studies have found that the risk of cardiovascular mortality is higher in women with diabetes than in men with diabetes [@huxley2006]
