---
title: "Introduction {.unnumbered}"
file: "intro.qmd"
---

This thesis is based on two studies examining the effect of sodium glucose co-transporter 2 (SGLT2)-inhibition on risk of cardiovascular disease and cardiovascular risk factors. The studies are presented as original papers published in international, peer-reviewed medical journals.\
SGLT2 inhibitors became available as treatment for type 2 diabetes in the early 2010s after they had been shown to improve glycemic control. Only a few years later, in 2015, results were published showing that, in addition to lowering blood glucose levels, SGLT2 inhibitor treatment also dramatically reduced the risk of hospitalization for heart failure and even mortality. These convincing effects had not been seen before with other glucose-lowering drugs and the mechanism behind was unclear. The following thesis is based on more than 4 years of work on conceiving, designing, conducting, and disseminating scientific studies to investigate potential mechanisms of the effect of SGLT2 inhibition on lower risk of cardiovascular disease and mortality.

**The aims** of the studies included in the thesis were to **1)** explore potential mediators of the effect of SGLT2 inhibition on risk of cardiovascular disease and quantify the mediated proportions using a genetic variant mimicking pharmacological SGLT2 inhibition in three large cohorts comprising more than 900 000 individuals, and **2)** to quantify the effect of pharmacological SGLT2 inhibition on lipid and lipoprotein levels in a meta-analysis of all SGLT2 inhibitor randomized placebo-controlled trials reporting on these.

In **Paper I**, we hypothesized that that a functional genetic variant in solute carrier family 5 member 2 (*SLC5A2*), known to be associated with familial renal glucosuria, would mimic pharmacological SGLT2 inhibition, and thus provide an opportunity to examine potential mediators of the effects on lower risk of cardiovascular disease and mortality. We hypothesized that carriers of the rare G-allele of the functional genetic variant rs61742739 in *SLC5A2*, known to cause familial renal glucosuria, have a life-long altered function in SGLT2 and therefore lower risks of cardiovascular disease and mortality, comparable to the lower risks seen in SGLT2 inhibitor trials. Furthermore, we hypothesized that variation in rs61742739 could be used to examine potential mediators of the effects of SGLT2 inhibition on cardiovascular disease and mortality, such as plasma glucose, body mass index, blood pressure, plasma creatinine, plasma sodium, plasma potassium, blood hematocrit, and plasma lipids. We found that carriers of the rare G-allele of rs61742739 in *SLC5A2* had lower risks of heart failure, myocardial infarction, ischemic heart disease and all-cause mortality in the general population and that the effects were at most minimally mediated through a lower plasma glucose.\
In **Paper II**, we hypothesized that treatment with SGLT2 inhibitors affected levels of lipids and lipoproteins, some of which are known to be causally associated with cardiovascular disease. We included all available randomized placebo-controlled trials of SGLT2 inhibitors and stratified the analyses by treatment dose, non-Asian/Asian ethnicity, and by type of SGLT2 inhibitor. We found that SGLT2 inhibition modestly increased total, LDL, and HDL cholesterol and modestly lowered triglycerides, and that effect sizes varied slightly by drug dose and ethnicity but were generally robust by drug type.

The results of the two studies add to the understanding of the mechanism behind the lower risks of cardiovascular disease with SGLT2 inhibitor treatment, or more precisely, highlight that lower plasma glucose and changes in lipids and lipoproteins are not likely to explain a large part of the lower risks. These findings are important because a deeper understanding of this mechanism may provide opportunities for improved use of pharmacological SGLT2 inhibitor treatment. Further studies on the topic are warranted for a full mechanistic understanding.

The thesis consists of three parts. Part 1 is a narrative review of the literature on SGLT2 inhibition and risk of cardiovascular disease and mortality, where the findings of the two included original studies are discussed in the context of the current knowledge in the field. Part 2 is an expansion on and a critical review of the methods used in the two included studies. Part 3 consists of the two included original papers.

\newpage
