---
title: "Part 1: Potential mediators from SGLT2 inhibition to reduced risk of cardiovascular disease and mortality" 
file: "part1_sglt2_review.qmd" 
bibliography: references.bib
---

\pagebreak

## Abstract

Sodium glucose co-transporter 2 (SGLT2) inhibitors were developed as glucose-lowering drugs for the treatment of type 2 diabetes mellitus and went on the market in the early 2010's. Only a few years later, they were shown to have surprisingly beneficial effects on risk of cardiovascular disease and mortality, however, by an unknown mechanism.\
Both hyperglycemia and hyperlipidemia are known risk factors for cardiovascular disease and mortality. The causal contributions of elevated glucose, low-density lipoprotein (LDL) cholesterol, and triglyceride levels to atherosclerotic cardiovascular disease are well-established in observational and genetic studies, but whether changes to these are involved in the mechanism behind lower risk of cardiovascular disease and mortality observed with SGLT2 inhibitor treatment is unclear. The aim of this review is to give an introduction to SGLT2 and SGLT2 inhibitors, summarize the current evidence of the effects of hyperglycemia and hyperlipidemia on risk of cardiovascular disease, and review the effects of SGLT2 inhibitors on these risk factors and outcomes.

\pagebreak

## Sodium glucose co-transporter 2 - the perfect drug target?

SGLT2 inhibitors were developed as treatment for type 2 diabetes mellitus. The idea behind was simple and obvious: if there is a problem of excess glucose in the bloodstream, it can potentially be solved by increasing the loss of glucose in the kidneys. SGLT2, the main driver for glucose reabsorption in the proximal tubule of the nephron, was the ideal target since the transporter is responsible for \~90% of glucose reuptake following the primary filtration in the glomerulus[@coady2017] (@fig-1).\

![Sodium glucose co-transporter 2 (SGLT2) is located on the luminal side of the tubule cells in the proximal tubule of the nephron in the kidney. Glucose enters the cell in Na^+^-coupled transport driven by the Na^+^ gradient created by the Na^+^/K^+^-ATPase on the interstitial side. Glucose leaves the cell largely through GLUT2 and diffuses passively to the peritubular vessel. SGLT2 is responsible for \~90% of glucose reabsorption in the kidneys. Image created with BioRender.](sglt2.png){#fig-1 width="80%"}

Early studies of SGLT2 physiology were conducted well before the actual discovery of SGLT2. In 1835, phlorizin - a naturally occurring phenol glucoside and SGLT2 inhibitor - was first isolated from apple tree bark[@koninck1836], and studies in the 1880s showed that the administration of this isolate caused renal glucosuria[@jörgens2020]. It was, however, not until the 1980s that studies of phlorizin as a blocker of renal tubular glucose reabsorption gained traction[@starke1985; @rossetti1987], and that the connection to the phlorizin-like phenotype of familial renal glucosuria was found to be caused by genetic variation in the gene encoding SGLT2[@hediger1989; @kanai1994].

The first SGLT2 inhibitors or gliflozins were marketed in the early 2010s as a novel oral antidiabetic treatment, shown to reduce plasma glucose and weight[@nair2010]. Then, when results from large scale cardiovascular outcome trials came out a few years later, type 2 diabetes mellitus treatment suddenly faced a shift in treatment paradigm: Up until 2015, treatment for type 2 diabetes had mainly been focused on lowering plasma glucose with glucose-lowering drugs, while also targeting cardiovascular risk with lipid-lowering therapy, antihypertensive treatment, and improved lifestyle, but the results of the EMPA-REG OUTCOME trial revealed the potential of pharmacologically reducing glucose levels along with reducing the risk of cardiovascular disease and mortality, further adding to the effect of lipid-lowering and antihypertensive therapy. The EMPA-REG OUTCOME study group found a 35% (95% CI: 15-50) lower risk of hospitalization for heart failure, a 38% (23-51) lower risk of cardiovascular mortality, and a 32% (18-43) lower risk of all-cause mortality for empagliflozin compared to placebo[@zinman2015]. In the following years, similar effects were also found for other SGLT2 inhibitor types[@wiviott2019; @neal2017;@cannon2020] (@fig-2) and it became evident that SGLT2 inhibitors not only had the potential to change diabetes treatment, but also to prevent cardiovascular outcomes in other at-risk populations[@petrie2020; @bays2014; @mcmurray2019; @packer2020].

![Meta-analysis of cardiovascular risk in individuals with diabetes in SGLT2 inhibitor cardiovascular outcome trials. Adapted from McGuire et al.[@mcguire2021].](meta_risk.png){#fig-2}

As a consequence, the SGLT2 inhibitors empagliflozin and dapagliflozin are now included as class 1 recommended treatments for heart failure with reduced ejection fraction in individuals without diabetes in both European and American guidelines[@authors/taskforcemembers:2022; @heidenreich2022].

Although several processes that may lead to cardiovascular disease are impacted by the metabolic changes that characterize type 2 diabetes, the main focus in this review will be on hyperglycemia and hyperlipidemia to provide a framework for the examinations of the relationship between SGLT2 inhibition and cardiovascular disease in the two original papers included in the thesis. Likewise, the mechanistic considerations for the effect of SGLT2 inhibition on cardiovascular disease and mortality will be the most thorough for glucose, lipids, and lipoproteins and only to a limited extent for other potential mediators. The review of cardiovascular diseases in relation to diabetes and SGLT2 inhibition will be focused on heart failure and atherosclerotic cardiovascular disease.

## Risk factors for cardiovascular disease and potential mediators of SGLT2 inhibition

### Hyperglycemia and diabetes

The relationship between elevated plasma glucose or diabetes and increased cardiovascular risk is well-established[@emanuelsson2020; @benn2012; @ahmad2015; @dalcanto2019]. The increasing global epidemic of obesity and type 2 diabetes accounts for an increasing number of cardiovascular deaths[@ford2007] and cardiovascular disease is the main cause of morbidity and mortality in type 2 diabetes, where cardiovascular events occur 15 years earlier and are more severe than in individuals without diabetes[@dalcanto2019]. It is estimated that more than 50% of individuals with type 2 diabetes will die from a cardiovascular event[@dalcanto2019; @einarson2018].

For hyperglycemia, the increased risk of cardiovascular disease in the general population begins even within the normal plasma glucose range[@bechmann2023] (**Paper I,** @fig-glucose_spline).

![Risk of heart failure, myocardial infarction, ischemic heart disease, and all-cause mortality according to plasma glucose in the Copenhagen City Heart Study and Copenhagen General Population Study. Hazard ratios were estimated using Cox regression and restricted cubic splines. The light blue areas indicate the distribution of glucose concentrations in the populations. Cox regressions were adjusted for date of birth, sex, body mass index, blood pressure, low-density lipoprotein (LDL) cholesterol, high-density lipoprotein (HDL) cholesterol, triglycerides, and current smoking status. The median concentration of glucose was used as reference. Only individuals free of event at baseline were included. Adapted from Bechmann et al. (**Paper I)**. CI=confidence interval, HR=hazard ratio, N=number.](glucose_spline.png){#fig-glucose_spline}

Mendelian randomization studies have established the causal relationship between higher plasma glucose and risk of coronary heart disease[@emanuelsson2020; @benn2012; @ahmad2015], free from limitations such as confounding and reverse causation, which can be issues in observational analyses.\
Hyperglycemia pathophysiology in type 2 diabetes involves insulin resistance in muscle and liver tissue, impaired beta-cell glucose sensitivity, and an increased insulin secretion, creating a sequence of reciprocal cause and effect which intensifies and aggravates the high glucose level and its negative effects. Hyperglycemia may promote atherosclerosis by acting on several stages of the atherosclerotic process, i.e. endothelial function, metabolic pathways, inflammation, fibrous cap formation, and thrombosis[@laakso2014], and it may explain part of the increased risk of cardiovascular disease in diabetes. Furthermore, hyperglycemia drives structural changes through different pathogenic pathways which explain most diabetes complications[@basta2004; @deicas2015]. These mechanisms include the formation of advanced glycation end-products (AGEs) to an accelerated degree. AGEs are thought to promote atherogenesis by oxidizing low-density lipoproteins (LDLs) and cause changes to the collagen structure in the blood vessel intima[@basta2004]. Other hyperglycemia/diabetes-related complications have been proposed to be due to activation of the protein kinase C/diacylglycerol signaling pathway, increased levels of enzymes involved in cellular processes such as DNA repair and programmed cell death, and the oxidative stress from both mitochondrial and nonmitochondrial sources[@deicas2015]. However, reductions in plasma glucose alone have not convincingly been shown to reduce risk of cardiovascular disease[@advancecollaborativegroup2008; @duckworth2009; @intensiv1998; @actiontocontrolcardiovascularriskindiabetesstudygroup2008].

Several clinical trials have investigated the effect of glucose-lowering drugs on the risk of cardiovascular outcomes. The ADVANCE trial (Action in Diabetes and Vascular Disease: Preterax and Diamicron MR Controlled Evaluation), published in 2008, demonstrated that intensive glycemic control using gliclazides targeting an HbA1c level of 6.5% in individuals with type 2 diabetes did not result in a reduction of macrovascular events, nor mortality[@advancecollaborativegroup2008]. Additional support for these findings can be found in the 2009 Veterans Affairs Diabetes Trial (VADT)[@duckworth2009] and in the 1998 United Kingdom Prospective Diabetes Study (UKPDS)[@intensiv1998], where intensive glycemic control did not result in reduction in risk of major cardiovascular events or mortality over 7.5 and 10 years of follow-up, respectively. The ACCORD trial (Action to Control Cardiovascular Risk in Diabetes), published in 2008, aimed for an even lower HbA1c of 6% in the intensive therapy group, but unexpectedly observed a 22% increased risk of mortality, identifying a previously unrecognized risk associated with intensive glucose lowering in high-risk patients with type 2 diabetes[@actiontocontrolcardiovascularriskindiabetesstudygroup2008]. Due to the higher mortality, this arm of the trial was prematurely terminated.\
Type 2 diabetes is a complex disease and is often characterized as a largely lifestyle-associated disease, but while lifestyle contributes significantly to the development of type 2 diabetes, the Look AHEAD trial demonstrated that improving lifestyle did not improve cardiovascular risk in spite of weight loss and a decrease in HbA1c[@lookaheadresearchgroup2013].\
Collectively, these studies suggest that while hyperglycemia is a risk factor for cardiovascular disease and mortality, treatment with glucose-lowering drugs, or lifestyle improvements that lower HbA1c levels, might not translate into a sufficiently reduced cardiovascular risk, and in some cases, it may even increase the risk of cardiovascular events. Notably, none of the above-mentioned studies included SGLT2 inhibitor treatment.

#### Hyperglycemia, diabetes, and heart failure

Heart failure often occurs as a result of atherosclerosis that ultimately compromises myocardial blood flow or leads to myocardial infarction, causing ischemic cardiomyopathy, but it can also be the consequence of other disturbances[@dunlay2019; @kenny2019]. Both in individuals with and without diabetes, hypertension and chronic kidney disease are major risk factors for heart failure because of the increased cardiac load, eventually resulting in left ventricular hypertrophy. In diabetes, metabolic changes can lead to diabetic cardiomyopathy without other obvious causes for cardiomyopathy, such as hypertension, valve disease or ischemic heart disease[@kenny2019].\
Heart failure is a common and serious complication of diabetes and it has been found to be the most common presentation of cardiovascular disease after peripheral artery disease in individuals with type 2 diabetes[@shah2015]. Heart failure is 2 to 8 times more prevalent in individuals with diabetes compared to individuals without diabetes[@nichols2001], and it has been shown that a 1% increase in HbA1c is associated with an increase in risk of heart failure by 8 percent[@iribarren2001]. Higher New York Heart Association (NYHA) functional class has been shown to be associated with lower insulin sensitivity in individuals with heart failure but without a diabetes diagnosis[@doehner2005], further illustrating the relationship where diabetes and heart failure may result in further disease progression and a worse prognosis, in a manner where each disease independently increases the risk of the other because of different exacerbating factors.

The direct impact of hyperglycemia in heart failure development has been widely discussed. It has been proposed that alterations to cardiac metabolism found in individuals with diabetes may cause glycation and the formation of AGEs, and result in structural modifications to the myocardium that may then lead to heart failure[@deicas2015]. The impaired insulin sensitivity and hyperglycemia, that define diabetes, have consequences for numerous metabolic processes that together may lead to diabetic cardiomyopathy, characterized by functional and structural changes of the myocardium due to altered glucose and free fatty acid (FFA) metabolism. Insulin resistance in the diabetic heart causes impaired glucose uptake into the cardiomyocytes and leads to an increased release of FFAs. This change in substrate availability contributes to abnormalities in energy metabolism and cardiac dysfunction, observed in diabetic cardiomyopathy. Excessive FFA levels can cause lipid accumulation in cardiomyocytes, leading to lipotoxicity, contractile dysfunction, and eventually cardiomyocyte apoptosis[@lopaschuk2010].\
As the diabetic disease progresses, comorbidities as hypertension, dyslipidemia, obesity, renal disease, and microvascular and neurological complications are likely to further accelerate the heart failure progression. Additionally, oxidative stress from the elevated production of reactive oxygen species (ROS) and mitochondrial dysfunction may contribute to metabolic substrate dysregulation, cardiac remodeling, impaired calcium handling, and impaired contractility and relaxation of the myocardium[@marwick2018; @huynh2014].\
Hyperglycemia triggers the formation of AGEs, which induce collagen cross-linking and contribute to increased fibrosis of the myocardium. This fibrosis leads to heightened myocardial stiffness and impaired cardiac contractility and relaxation[@basta2004]. In addition, impaired calcium homeostasis regulation, due to altered expression and/or activity of several crucial proteins in the cellular membranes, interferes with cardiomyocyte contractility, and also contributes to cardiomyocyte fibrosis and diastolic dysfunction[@dobrin2010]. Hyperglycemia, systemically and locally, activates the renin-angiotensin-aldosterone system (RAAS), resulting in the overproduction of angiotensin II and aldosterone. This causes higher mean arterial pressure, and renal vascular resistance. These hormones promote cardiac hypertrophy and fibrosis[@lim2004; @waddingham2015].\
However, Mendelian randomization studies have not found an association between genetic determinants of fasting glucose or HbA1c and heart failure[@mordi2021], suggesting that the observational increased risk of heart failure seen with hyperglycemia (@fig-glucose_spline) might be due to confounding or reverse causation, and that other mechanisms are at play linking diabetes and heart failure. Also, in a meta-analysis of the ADVANCE, VADT, UKPDS, ACCORD, and 3 other trials, no association was found between intensive glycemic control and occurrence of heart failure events[@castagno2011]. In fact, intensive glycemic control with thiazolidinediones even increased the risk of heart failure.

### SGLT2 inhibitor effects on glycemic control

SGLT2 inhibitor treatment improves glycemic control almost immediately after treatment initiation. HbA1c levels are reduced with 0.7-0.8 percentage points after the first 3 months of treatment but the effect attenuates with longer treatment, with a mean reduction of 0.3 percentage points from baseline after 4 years of treatment[@zinman2015; @neal2017; @wiviott2019; @cannon2020]. Although, other glucose-lowering drugs have been shown to reduce cardiovascular risk[@ghosh-swaby2020], glucose-lowering drugs with similar glucose-lowering properties as SGLT2 inhibitors do, however, not affect cardiovascular risk equally, especially when it comes to risk of heart failure(@fig-meta_gluc_lowering).

![Meta-analysis estimates of risk of major cardiovascular event and hospitalization for heart failure for three different glucose-lowering drugs with similar glucose-lowering properties. Adapted from Ghosh-Swaby et. al[@ghosh-swaby2020]](meta_gluc_lowering.png){#fig-meta_gluc_lowering}

This has been one of the main arguments against improved glycemic control as the main driver behind lower risk of heart failure with SGLT2 inhibitors. Hyperglycemia is not known to causally associate with heart failure; however, genetic evidence has established hyperglycemia as a causal risk factor for coronary heart disease, and it is possible that the mechanisms behind the reduction in risk of heart failure and atherosclerotic/ischemic events are different.\
Empagliflozin and dapagliflozin have been investigated directly in individuals with heart failure with reduced ejection fraction (HFrEF) with and without diabetes in two large clinical trials, EMPEROR-Reduced[@packer2020] and DAPA-HF[@mcmurray2019]. Both studies convincingly showed lower risk of cardiovascular mortality and hospitalization for heart failure in individuals with HFrEF, which led to the recommendation that SGLT2 inhibitors should be used for treatment in HFrEF, regardless of diabetes status. SGLT2 inhibitors appear to be effective in the majority of heart failure subtypes, regardless of ejection fraction, and other potential influences such as estimated glomerular filtration rate, diabetes or the severity of the clinical picture[@girerd2023], also supporting the minimal role of glucose in the association between SGLT2 inhibition and risk of heart failure.\
Cardiovascular outcome trials of SGLT2 inhibitors have failed to show a reduction in risk of myocardial infarction[@zinman2015; @neal2017; @wiviott2019; @cannon2020], although there is an effect on the composite endpoint "Major Cardiovascular Event" which includes myocardial infarction(@fig-2). Bechmann et al. have shown that a genetic variant mimicking SGLT2 inhibition lowered risk of heart failure, myocardial infarction, ischemic heart disease, and all-cause mortality in the Danish general population[@bechmann2023] (**Paper I**, @fig-2_paper1) . The estimated lower risk of myocardial infarction may be due to the longer follow-up of \~42 years in this genetic cohort vs. the relatively short follow-up in cardiovascular outcome trials of \~4 years, which may not be sufficient to show a reduction in atherosclerotic events.

![A genetic variant in *SLC5A2*, the gene encoding SGLT2, lowered risk of heart failure, myocardial infarction, ischemic heart disease, and all-cause mortality in the Danish general population. Non-carriers (AA) of the variant were used as the reference. Hazard ratios were estimated using Cox regression with age as an underlying variable (=age adjusted) and all estimates were additionally adjusted for sex and date of birth. Only individuals free of event at baseline were included. Adapted from Bechmann et al.[@bechmann2023] (**Paper I)**. HR = hazard ratio, N = number.](figure2_paper1.png){#fig-2_paper1}

In an investigation of potential mediators of the effect of genetic variation in the gene encoding SGLT2 and the risk of heart failure, myocardial infarction, ischemic heart disease, and all-cause mortality, glucose was found to play only a minor role[@bechmann2023] (**Paper I)**. Indeed, lower plasma glucose mediated \<4% of the effect on lower risk of heart failure, myocardial infarction, ischemic heart disease, and all-cause mortality, supporting the hypothesis that other mechanisms are more important.

### Lipids and lipoproteins

Lipids and lipoproteins play a central role in the development and progression of atherosclerotic disease, a discovery that began to take shape in the beginning of the 20th century. German chemist, Adolf Windaus made a significant discovery which provided the initial indication that the substance present in atherosclerotic plaques was cholesterol. Windaus found that plaques taken from human aortas contained 25 times more cholesterol than healthy aortas. In 1913, the Russian pathologist Nikolaj Anitschkow conducted an experiment in which he fed rabbits pure cholesterol, resulting in the development of extensive atherosclerosis[@goldstein2015a]. This experiment was the first known attempt to causally link dietary cholesterol and the cholesterol deposits seen in atherosclerosis.\
Atherosclerotic plaques are formed as cholesterol and lipids accumulate in the arterial wall, triggering inflammation and further accumulation of cellular waste products, calcification, and the formation of a fibrous cap. This process can lead to several conditions depending on the localization and severity of the formed plaque. Frequent manifestations of atherosclerosis include coronary heart disease, ischemic stroke, peripheral artery disease, and heart failure, but also angina pectoris, transient ischemic attack, and aortic aneurysm. Diabetes frequently leads to development of structural heart disease through mechanisms involving myocardial ischemia or infarction[@deicas2015]. The atherosclerotic process is similar in individuals with and without type 2 diabetes but is aggravated by the metabolic changes that characterize type 2 diabetes such as insulin resistance, hyperglycemia, and disturbances in the carbohydrate-, fat- and protein metabolism that may induce vascular smooth muscle cell proliferation and inflammation.

Since the first discoveries by Windaus and Anitschkow, cholesterol has been extensively examined in relation to cardiovascular disease, and it is now well established that LDL cholesterol is causally associated with atherosclerotic cardiovascular disease[@ference2017]. This causal relationship is backed by multiple lines of evidence ranging from observational studies and randomized clinical trials to genetic evidence[@ference2017]. To in fact confer causality, certain criteria must be met. The relationship must rest on biological plausibility, the temporality of events must be in line with the causal chain, results must be consistent over a large number of different methods, subjects, localizations, and timepoints, the outcome most be specific to the exposure, and in the case of risk associations; a change in risk must be seen with a change in exposure[@hill1965; @altman2015; @ference2017]. For LDL cholesterol and risk of atherosclerosis, all of these have been fulfilled. It is well-established that LDL particles enter the arterial intima, and that this process accelerates with higher concentrations of LDL cholesterol in the blood, leading to the development of atherosclerotic plaques[@goldstein2015a]. The genetic disease, familial hypercholesterolemia, is characterized by distinctly elevated levels of LDL cholesterol[@najam2015]. Compared to their siblings without a disease causing mutation, individuals with familial hypercholesterolemia have elevated LDL cholesterol levels and a corresponding, dose-dependent elevated lifetime risk of atherosclerotic cardiovascular disease, providing compelling evidence that LDL causes atherosclerosis and cardiovascular disease[@wiegman2015]. The dose-response relationship is further substantiated by the fact that different familial hypercholesterolemia mutations, which give rise to different degrees of elevated LDL cholesterol, correspond to different degrees of elevated lifetime risk of atherosclerosis and cardiovascular disease[@cohen2006]. While the association between LDL cholesterol and atherosclerotic cardiovascular disease is strong and has been reproduced numerous times in observational studies of prospective cohorts[@prospectivestudiescollaboration2007], these types of studies, being vulnerable to reverse causation and confounding, cannot sufficiently fulfill the requirements of temporality and specificity required to make the convincing argument for causality. The results of Mendelian randomization studies, however, resolve these issues, as they have convincingly shown that variants in more than 50 genes, associated with lower LDL cholesterol levels (but not with other risk factors for atherosclerotic cardiovascular disease), are also associated with a lower risk of cardiovascular disease[@cohen2006; @nikpay2015; @holmes2015; @ference2017].\
Years of research further support the association between other apolipoprotein B-containing lipoproteins, such as very low-density lipoproteins (VLDL), intermediate density lipoproteins (IDL), and lipoprotein(a), with the development and progress of atherosclerotic cardiovascular disease[@libby2011; @kamstrup2016; @goldstein2015a].\
In the Framingham Heart Study - one of the first long-term cohort studies and part of the foundation in modern epidemiology - HDL was found to be strongly and inversely associated with atherosclerotic cardiovascular disease[@gordon1977]. While knowledge of the relationship between low HDL cholesterol levels and atherosclerosis was not entirely new, publications on HDL cholesterol from The Framingham Heart Study laid the groundwork for decades of recommendations on cholesterol and risk of cardiovascular disease, research in the field, and for numerous studies aiming to raise HDL cholesterol levels with the purpose of lowering cardiovascular risk.\
Studies of cholesteryl ester transfer protein (CETP) inhibitors, that raise HDL cholesterol levels by targeting the lipoprotein metabolism, indeed succeeded in raising HDL cholesterol levels, but were either terminated prematurely due to an increased risk of death and cardiovascular events[@barter2007] or lack of efficacy [@schwartz2012; @lincoff2017]. One CETP inhibitor study showed a lower incidence of major coronary events[@hps3/timi55-revealcollaborativegroup2017] but this was likely because of the beneficial effects on LDL cholesterol and triglyceride-rich lipoproteins[@kjeldsen2022]. The HPS2-THRIVE study examined the effect of niacin, also known to raise HDL cholesterol levels, and found no effect on cardiovascular risk but instead an increased risk of adverse events.\
The history of HDL cholesterol clearly demonstrates the risk of reverse causation and confounding in observational studies, further emphasized by recent years of genetic studies dismissing a causal relationship between HDL cholesterol levels and risk of atherosclerotic disease. Mendelian randomization studies have identified several genetic variants that cause higher HDL cholesterol levels without reducing risk of atherosclerotic disease[@do2013; @white2016; @richardson2020]. Additionally, some genetic variants, that are associated with higher HDL cholesterol levels, have been associated with high risk of cardiovascular disease[@agerholm-larsen2000; @andersen2003; @frikke-schmidt2008], further complicating the understanding of the relationship. Further, both low and high levels of HDL cholesterol have been shown to be associated with all-cause mortality[@madsen2017; @zhong2020; @mørland2023]. Analyses of cause specific mortality have revealed that the U-shaped relationship also exists within cancer mortality and other non-cardiovascular mortality[@madsen2017; @zhong2020; @mørland2023].\
For several years since the beginning of the understanding of the role of lipids and lipoproteins in cardiovascular disease, the main focus was on LDL and HDL cholesterol, with less interest in triglycerides. However, there is consistent evidence that elevated levels of triglyceride-rich lipoproteins, marked by elevated levels of plasma triglycerides, increase the risk of cardiovascular disease[@hokanson1996; @jørgensen2013; @thomsen2014], and that it might be because of the cholesterol content in triglyceride-rich lipoproteins (also called remnant cholesterol) and not because of the triglycerides as such. Chylomicrons, consisting mainly of triglycerides, are too large to enter the arterial intima, and are therefore not likely to be directly involved in the atherosclerotic process. However, remnants can enter the arterial wall and this may lead to low-grade inflammation, foam cell and plaque formation, and in the end, cardiovascular disease and increased risk of mortality[@nordestgaard2014a].\
Lipoprotein(a) is also thought to be able to penetrate the arterial intima, similar to LDL and remnants, and to be highly atherogenic[@rehbergerlikozar]. Epidemiological and genetic studies provide convincing evidence of lipoprotein(a) being a causal factor in the development of cardiovascular disease[@emergingriskfactorscollaboration2009; @kamstrup2016]. While LDL cholesterol and triglyceride levels in general are modifiable by lifestyle and/or pharmacological treatment, lipoprotein(a) levels are 70-90% genetically determined[@schmidt2016] and there are few real treatment options for lowering lipoprotein(a), although several new and promising drugs are in development[@sosnowska2022].

### SGLT2 inhibitor effects on lipids and lipoproteins

Being causal risk factors for cardiovascular disease, LDL cholesterol and triglyceride-rich lipoproteins, marked by elevated levels of plasma triglycerides, had to be examined in relation to SGLT2 inhibitors as part of the drug development process. The primary investigation of this took place in the early stages of drug development. However, as animal studies did not reveal any effects of SGLT2 inhibitors on lipids and lipoproteins, and as there is no clear mechanistic link between SGLT2 and lipid metabolism, this relationship has not been broadly studied. As the number of published randomized controlled trials of SGLT2 inhibitors increased, a pattern was nonetheless forming, showing that, unlike in animals, SGLT2 inhibitors affected lipid and lipoprotein levels in humans. In a meta-analysis of 60 randomized placebo-controlled trials, Bechmann et al. found that SGLT2 inhibition modestly increased total, LDL, and HDL cholesterol and modestly decreased plasma triglycerides[@bechmann2023a] (**Paper II**, @fig-meta_sglt2_lipids).

![Meta-analysis estimates for the effect of SGLT2 inhibitor treatment on lipids and lipoproteins. Meta-analysis estimates of the mean difference of the effect of SGLT2 inhibitor treatment versus placebo on plasma total cholesterol, low density lipoprotein (LDL) cholesterol, high density lipoprotein (HDL) cholesterol, and plasma triglycerides. Random effects meta-estimates were calculated using the metafor R package as raw mean differences, shown for each lipid and lipoprotein with 95% confidence intervals in mmol/L and mg/dL. If the mean change from baseline was reported along with a variance statistic, this was preferred for the meta-analysis, otherwise the measurements at follow-up were used. The shown I^2^s, as measures of between study heterogeneity, are from the random effects models. Adapted from Bechmann et al.[@bechmann2023a] (**Paper II)**. CI = confidence interval, N = number. ](meta_sglt2_lipids.png){#fig-meta_sglt2_lipids}

The mechanism behind these effects is largely unknown and has not been thoroughly investigated. Basu et al.[@basu2018] studied the mechanism behind the increased LDL cholesterol and decreased triglyceride levels with SGLT2 inhibition using a mouse model expressing human CETP and apolipoprotein B100 (ApoB100). Mice (n = 40) were assigned to 1 of 4 treatments, vehicle, canagliflozin, an SGLT2 antisense oligonucleotide, or insulin. In the canagliflozin group, the effects on LDL cholesterol and triglycerides were similar to the effects seen in human studies, showing a slight increase in LDL cholesterol and a decrease in triglycerides. To investigate changes in lipoprotein physiology, lipoprotein lipase (LpL) activity, LDL receptor and post transcriptional modulator 9 (PCSK9) expression, and angiopoietin-like protein 4 (ANGPTL 4) expression were assessed, and the conclusion of the study was that SGLT2 inhibitor and SGLT2 antisense oligonucleotide treatment increased plasma lipolytic activity and LpL activity, possibly because of reduced expression of ANGPTL4, especially in the SGLT2 antisense oligonucleotide treated mice. This might explain the reduction in triglyceride levels. Furthermore, the increase in LDL cholesterol could be due to increased VLDL to LDL turnover and a reduced LDL clearance, possibly because of reduced LDL receptor and PCSK9 expression seen in the SGLT2 antisense oligonucleotide group.\
In a human study, including 80 individuals assigned to either dapagliflozin or dipeptidyl peptidase-4 (DPP-4) inhibitor sitagliptin, the dapagliflozin group experienced no significant change in LDL cholesterol levels after 12 weeks of treatment. However, there was a notable decrease of 20% in small dense LDL cholesterol levels, accompanied by an increase of 18% in large buoyant LDL cholesterol levels [@hayashi2017]. Another study, comparing ipragliflozin to continued usual treatment in individuals with type 2 diabetes, revealed reductions in total, LDL cholesterol, and small dense LDL cholesterol levels in the ipragliflozin group when compared to baseline[@bando2016]. LDL cholesterol comprises various subfractions, giving rise to a heterogeneous group of particles with different sizes and densities, ranging from very small to large. Elevated levels of small and dense LDL particles have been linked to an increased risk of cardiovascular disease, regardless of other LDL subfractions[@carmena2004; @duran2020]. Small dense LDL particles tend to circulate in the bloodstream longer than larger LDL particles. Moreover, they are believed to have a higher tendency to penetrate the arterial wall's intima and are more susceptible to oxidation, potentially increasing their atherogenic potential [@balling2023; @krauss2022]. However, further studies are needed to understand the relationship between SGLT2 inhibition, LDL cholesterol subfractions, and cardiovascular risk.

The clinical relevance of the modest increases in total, LDL, and HDL cholesterol and modest decrease in triglycerides seen with SGLT2 inhibitor treatment is likely to be negligible. Individuals with type 2 diabetes and/or heart failure, who typically receive SGLT2 inhibitor treatment, should be closely monitored for dyslipidemia and treated according to existing guidelines. However, elucidating the effect of SGLT2 inhibitors on lipid metabolism is important to fully understand the relationship between SGLT2 inhibition and cardiovascular disease. In another study, Bechmann et al. used a genetic variant mimicking SGLT2 inhibition to examine the effect on potential mediators of lower risk of cardiovascular disease and mortality and found no effect of the genetic variant on levels of LDL and HDL cholesterol, nor on triglycerides[@bechmann2023] (**Paper I)**. In the Danish general population, there was however a small effect on lipoprotein(a), where each rare allele of the genetic variant was associated with 1.77 mg/dL (0.10-3.44) lower lipoprotein(a)[@bechmann2023] (**Paper I)**, a finding that needs to be confirmed in other studies.

## Conclusion

The first SGLT2 inhibitors, introduced in the early 2010s, marked a significant shift in the type 2 diabetes treatment paradigm. The EMPA-REG OUTCOME trial demonstrated a remarkable reduction in risk of hospitalization for heart failure, cardiovascular mortality, and all-cause mortality with the SGLT2 inhibitor empagliflozin. Subsequent studies of other SGLT2 inhibitors corroborated these effects and highlighted that the potential of SGLT2 inhibitors extended beyond diabetes treatment, since the reduced risk of cardiovascular outcomes were shown in individuals both with and without diabetes. Despite the well-established link between hyperglycemia and cardiovascular risk, evidence from various trials has demonstrated that glucose-lowering drugs, while effectively reducing HbA1c levels, do not consistently reduce cardiovascular risks, and concerns of increased risk have even been raised in some instances. This suggests that the beneficial cardiovascular effects of SGLT2 inhibition are not likely to be mediated through glucose-lowering, which is supported by genetic studies. The relationship between lipids, lipoproteins, and atherosclerotic cardiovascular disease has been extensively studied over the years, resulting in a thorough understanding of the atherosclerotic process. Cholesterol, particularly LDL cholesterol, has emerged as a causal factor in the initiation of atherosclerotic plaques, substantiated by evidence from observational and genetic studies and from randomized trials. Similarly, triglyceride-rich lipoproteins and lipoprotein(a) have been implicated in atherosclerosis. SGLT2 inhibitors modestly elevate LDL, HDL and total cholesterol and modestly lower plasma triglycerides. While these effects are unlikely to be of clinical importance and unlikely to mediate the beneficial effects of SGLT2 inhibition on cardiovascular disease, studying the mechanism behind the effects is important to elucidate the relationship between SGLT2 inhibition, lipid metabolism, and risk of cardiovascular disease.

\pagebreak
