---
title: "raas"
---

Further illustrating the interlaced mechanisms and complicated cause and effect relationships between hyperglycemia or type 2 diabetes and heart failure, studies have shown that angiotensin II receptor blocker Valsartan, an antihypertensive used in treatment heart failure, improves glycemic control. In the NAVIGATOR trial, 9306 patients with impaired glucose tolerance and established cardiovascular disease or cardiovascular risk factors were randomized to receive valsartan or placebo. In the treatment group, the hazard ratio for diabetes was 0.86 (95% confidence interval: 0.80-0.92, p\<0.001), whereas the incidence of cardiovascular outcomes remained unchanged [@navigatorstudygroup2010a]. In the DREAM trial, 5269 individuals with impaired fasting glucose levels or glucose tolerance without cardiovascular disease were randomized to ACE-inhibitor ramipril or placebo. The incidence of diabetes or death and median fasting plasma glucose levels did not differ between groups at the end of trial but participants in the treatment group were more likely to have regression to normoglycemia and had a better response to oral glucose tolerance tests[@dreamtrialinvestigators2006].\
In a subgroup of participants of the PARADIGM-HF trial, 3778 individuals with diabetes and heart failure with reduced ejection fraction were randomized to receive combined angiotensin II receptor blocker and neprilysin inhibitor sacubitril/valsartan, a drug that has been shown to reduce morbidity and mortality in heart failure[@mcmurray2014], or ACE-inhibitor enalapril. Neprilysin is a widely expressed enzyme involved in the breakdown of angiotensin I and II, bradykinin, and glucagon-like peptide 1 (GLP-1). Mean HbA1c levels were reduced more and new use of insulin was 29% lower in the in the sacubitril/valsartan group compared to the enalapril group, suggesting that sacubitril/valsartan might enhance glycemic control in patients with diabetes and HFrEF. In addition to the effects on the renin-angiotensin system, the inhibition of the neprilysin might improve glycemic control through mechanisms related to increases in circulating GLP-1, natriuretic peptides and an altered lipid metabolism[@seferovic2017].
