---
title: "Resumé på dansk{.unnumbered}"
---

Sodium glucose co-transporter 2 (SGLT2)-hæmmere blev udviklet som behandling for type 2-diabetes og blev tilgængelige på markedet i begyndelsen af 2010'erne. I 2015 blev der første gang publiceret resultater, der viste, at udover at sænke blodsukkerniveauet, reducerede SGLT2-hæmmerbehandling overraskende nok også risikoen for indlæggelse på grund af hjertesvigt, større kardiovaskulære hændelser (major cardiovascular events) og dødelighed. Mekanismen bag var dog uklar.\
Glukose, low-density lipoprotein (LDL) kolesterol og triglycerid-rige lipoproteiner er alle blevet vist at være involveret i udviklingen af hjertekarsygdomme, men spørgsmålet, om de gavnlige virkninger af SGLT2-hæmning på hjertekarsygdomme og dødelighed var medieret gennem ændringer i disse, var uløst.\
Vi opstillede hypotesen 1) at en funktionel genetisk variant i solute carrier family 5 member 2 (*SLC5A2*), kendt for at være associeret med familiær renal glukosuri, ville imitere farmakologisk SGLT2-hæmning og give mulighed for at undersøge potentielle mediatorer af effekterne på lavere risiko af hjertekarsygdomme og dødelighed i tre forskellige kohorter. Vi fandt, at bærere af det sjældne allel havde lavere risiko for hjertesvigt, myokardieinfarkt, iskæmisk hjertesygdom og dødelighed af alle årsager i den almindelige befolkning, og at virkningerne højst var minimalt medieret gennem lavere plasmaglukose.\
Vi opstillede hypotesen 2) at behandling med SGLT2-hæmmere påvirkede niveauet af lipider og lipoproteiner. Vi inkluderede alle tilgængelige randomiserede, placebokontrollerede forsøg med SGLT2-hæmmere og stratificerede analyserne efter behandlingsdosis, ikke-asiatisk/asiatisk etnicitet og efter type af SGLT2-hæmmer. Vi fandt, at SGLT2-hæmning i beskedent omfang øgede total-, LDL- og high-density lipoprotein (HDL)-kolesterol og beskedent sænkede triglycerider.\
Vores resultater tyder på, at mekanismen bag den lavere risiko for kardiovaskulær sygdom og dødelighed, set med SGLT2-hæmning, ikke skyldes ændringer i plasmaglukose eller ændringer i lipid- og lipoproteinniveauer, da vi fandt, at lavere plasmaglukose kun medierede en meget lille del af de lavere risici, og at ændringer i lipider og lipoproteiner var beskedne og med begrænset klinisk relevans. Vores undersøgelser er vigtige for at belyse virkningerne af SGLT2-hæmmerbehandling. Yderligere undersøgelser er nødvendige for en fuld mekanistisk forståelse af sammenhængen mellem SGLT2-hæmmerbehandling og lavere risiko for hjertekarsygdomme og død.\
\newpage
